import type { NextPage } from "next";
import Head from "next/head";
import styles from "../../styles/Home.module.css";
import { InputArea } from "../components/InputArea";
import { DisPlayArea } from "../components/DisplayArea";
import { Toaster } from "react-hot-toast";
import { GraphArea } from "../components/GraphArea";
import { useState } from "react";

const Home: NextPage = () => {
  const [displayChangeFlag, setDisplayChangeFlag] = useState(true);
  return (
    <>
      <Head>
        <title>Health App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <header>
          <h1 className="text-xl p-2 text-cyan-900">Health App!</h1>
        </header>
        <main className={styles.main}>
          <InputArea />
          <div className="flex mt-6 bg-cyan-900 text-white">
            <button
              className="border-white border"
              onClick={() =>
                displayChangeFlag
                  ? displayChangeFlag
                  : setDisplayChangeFlag(!displayChangeFlag)
              }
            >
              一覧
            </button>
            <button
              className="border-white border"
              onClick={() =>
                displayChangeFlag
                  ? setDisplayChangeFlag(!displayChangeFlag)
                  : displayChangeFlag
              }
            >
              グラフ
            </button>
          </div>
          {displayChangeFlag ? <DisPlayArea /> : <GraphArea />}
        </main>
        <footer></footer>
      </div>
      <Toaster />
    </>
  );
};

export default Home;
