import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import { InputArea } from "../components/InputArea";
import { DisPlayArea } from "../components/DisplayArea";

const Home: NextPage = () => {
  interface data {
    weight: string;
    fatPercent: string;
    visceralFatLevel: string;
    bmi: string;
  }

  const [data, setData] = useState<data[]>([]);
  const [record, setRecord] = useState({
    weight: "",
    fatPercent: "",
    visceralFatLevel: "",
    bmi: "",
  });

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setRecord((prev) => ({
      ...prev,
      [e.target.name]: e.target.value,
    }));
  };
  const handleClick = () => {
    setData((data) => [...data, record]);
    setRecord({
      weight: "",
      fatPercent: "",
      visceralFatLevel: "",
      bmi: "",
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Health App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>Health App!</h1>
      </header>
      <main>
        <InputArea
          handleChange={handleChange}
          handleClick={handleClick}
          record={record}
        />
        <DisPlayArea data={data} />
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
